# PERHATIKAN BARIS PERTAMA INI HARUS SAMA
[connections.supabase] 
dialect = "postgresql"
host = "db.ffoshpfzwjpjuauujmkg.supabase.co"
port = "5432"
database = "postgres"
username = "postgres"
password = "FY5Kw8FU0shYjnal"